### ISSUE TITLE
Decide on relationship between descending limb and descending thin limb of loop of Henle

### ISSUE THREAD

**Issue by dosumis** [obophenotype/asct-b_validation#23]
There is currently no is_a, part_of or overlaps relationship between these 2 classes.  

* descending thin limb http://purl.obolibrary.org/obo/UBERON_0005096 
* descending limb of loop of Henle http://purl.obolibrary.org/obo/UBERON_0001289

Should there be?

Original report 
n | s | slabel | user_slabel | o | olabel | user_olabel
-- | -- | -- | -- | -- | -- | --
  2 | UBERON:0005096 | descending thin limb | descending thin limb of loop of Henle | UBERON:0001289 | descending thin limb of loop of Henle | Loop of Henle (Thin Limb)

1289 - Descending limb of loop of Henle - "proximal part of loop of Henle"; 5096 = 'descending thin limb - "part of the loop of Henle situated just after the proximal straight tubule (S3)

**Comment by paolaroncaglia** [comment]
@dosumis @emquardokus 
As we haven't yet found a solution for this issue, I opened https://github.com/obophenotype/uberon/issues/2276 to ask for expert feedback on resolving this. If you'd like to email other specialists and point them to either ticket to enter their comments, please feel free to. Thanks.

**Comment by paolaroncaglia** [comment]
@dosumis @emquardokus I'm closing this, as it will be addressed by my resolution in https://github.com/obophenotype/uberon/issues/2276#issuecomment-1081963066. If you have any objection, please comment there. Thank you both and have a good (meeting) day!
