### ISSUE TITLE
[DRAFT] ASCT-B Table

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/asct-b_validation#33]
| Organ         | Graph     | Unvalidated Edges | New Cell Types         |     Notes     | Priority |
|--------------|-----------|------------|--------------|---------------|------------|
| Bone-Marrow |[Bone-Marrow graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Bone-Marrow_graph.png) | [Bone-Marrow unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Bone-Marrow_log.tsv) | [Bone-Marrow new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Bone-Marrow.tsv) | Very little of this validates. Most edges should probably be converted to has_part  | Low 
|Brain| [Brain graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Brain_graph.png)| [Brain unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Brain_log.tsv)|[Brain new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Brain.tsv)|Some issue with partonomy.  Need to check who experts were on this.  Could potentially replace with ABA IDs and directly re-use ABA partonomy. This came directly from Allen Brain Institute.|Low
  Blood | [Blood graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Blood_graph.png)|[Blood unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Blood_log.tsv)| [Brain new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Blood.tsv)|Very little of this validates.  Most edges should probably be converted to has_part|Low
 Eye|[Eye graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Eye_graph.png)|[Eye unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Eye_log.tsv)|[Eye new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Eye.tsv)|Table looks reasonably high quality. Plenty to discuss and fix. Some obvious errors in table;  A few issues on anatomical partonomy. Bigger issues around partonomy for cell types.  Lots of new cell types.|Medium/High
|Fallopian_tube|[Fallopian_tube graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Fallopian_tube_graph.png)| [Fallopian_tube unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Fallopian_tube_log.tsv)| [Fallopian _tube new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Fallopian_tube.tsv)| | |
|Heart|[Heart graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Heart_graph.png) | [Heart unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Heart_log.tsv) | [Heart new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Heart.tsv)|Graph looks scary, but very many cases might be fixed by making general terms in subject position specific.  Look at adding using table.  Also some interesting potential improvements to Uberon (e.g. sinoatrial node)|Medium: Tackle the X part_of Y terms and revisit graph later.
Kidney|[Kidney graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Kidney_graph.png)|[Kidney unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Kidney_log.tsv)|[Kidney new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Kidney.tsv)|Not so much left to fix.|High
Knee|[Knee graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Knee_graph.png)|[Knee unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Knee_log.tsv)|[Knee new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Knee.tsv)|Requires general discussion on modelling of joints. Include Meghan.|Low/Medium - revisit once we have better agreement on how to model joints.
Large_intestine|[Large_intestine graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Large_intestine_graph.png)|[Large_intestine unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Large_intestine_log.tsv)|[Large_intestine new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Large_intestine.tsv)|Graph looks terrifying. We may be able to tame it by adding lots of x part_of y terms. Add as many of these as possible & then revisit.|Low/medium.
Liver|[Liver graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Liver_graph.png)|[Liver unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Liver_log.tsv)|[Liver new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Liver.tsv)| | |
Lung|[Lung graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Lung_graph.png)|[Lung unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Lung_log.tsv)|[Lung new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Lung.tsv)| | |
Lymph_node|[Lymph_node graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/graphs/ccf_Lymph_node_graph.png)|[Lymph_node unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/class_Lymph_node_log.tsv)|[Lymph_node new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Lymph_node.tsv)|Anatomy looks OK and might be easy(ish) to fix.  Cell types are mostly general, so we probably should not bother to fix.|Medium (This table is a priority for the ASCT+B project)
Lymph_vasculature|[Lymph_vasculature graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Lymph_vasculature_graph.png)|[Lymph_vasculature unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Lymph_vasculature_log.tsv)|[Lymph_vasculature new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Lymph_vasculature.tsv)| | |
Ovary|[Ovary graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Ovary_graph.png)|[Ovary unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Ovary_log.tsv)|[Ovary new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Ovary.tsv)| | |
Pancreas|[Pancreas graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Pancreas_graph.png)|[Pancreas unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Pancreas_log.tsv)|[Pancreas new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Pancreas.tsv)| | |
Peripheral_nervous_system|[Peripheral_nervous_system graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Peripheral_nervous_system_graph.png)|[Peripheral_nervous_system unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Peripheral_nervous_system_log.tsv)|[Peripheral_nervous_system new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Peripheral_nervous_system.tsv)|Huge project, multi-stage in collaboration with SPARC consortium|Low/Medium
Prostate|[Prostate graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Prostate_graph.png)|[Prostate unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Prostate_log.tsv)|[Prostate new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Prostate.tsv)| | |
Skin|[Skin graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Skin_graph.png)| [Skin unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Skin_log.tsv)| [Skin new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Skin.tsv)|Collaboration and multiple manuscripts with GE for data/ASCT+B connection|Medium/High
Small_intestine|[Small_intestine graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Small_intestine_graph.png)|[Small_intestine unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Small_intestine_log.tsv)|[Small_intestine new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Small_intestine.tsv)| | |
Spleen|[Spleen graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Spleen_graph.png)|[Spleen unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Spleen_log.tsv)|[Spleen new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Spleen.tsv)| | |
Thymus|[Thymus graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Thymus_graph.png)|[Thymus unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Thymus_log.tsv)|[Thymus new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Thymus.tsv)| | |
Ureter|[Ureter graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Ureter_graph.png)|[Ureter unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Ureter_log.tsv)|[Ureter new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Ureter.tsv)| | |
Urinary_bladder|[Urinary_bladder graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Urinary_bladder_graph.png)|[Urinary_bladder unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Urinary_bladder_log.tsv)|[Urinary_bladder new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Urinary_bladder.tsv)| | |
Uterus|[Uterus graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Uterus_graph.png)|[Uterus unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Uterus_log.tsv)|[Uterus new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Uterus.tsv)| | |
Blood_vasculature|[Blood_vasculature graph](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//graphs/ccf_Blood_vasculature_graph.png)|[Blood_vasculature unvalidated edges](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/class_Blood_vasculature_log.tsv)|[Blood_vasculature new cell types](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master//logs/new_cl_terms_Blood_vasculature.tsv)|High value, Griffin Weber Vascular CCF paper, coordinate with manuscript submission?|High

**Comment by bvarner-ebi** [comment]
Plan to copy to #31

**Comment by bvarner-ebi** [comment]
@dosumis, @emquardokus, if the table above looks OK, I can move it to #31.

**Comment by emquardokus** [comment]
@bvarner-ebi yes, I think bought we confirmed during meeting earlier today. Thanks, I'll update priorities once I finish going through all the new logs.
