### ISSUE TITLE
Unmapped fibroblast terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#38]
_Logs from [2022-09-20 release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-09-20/logs/error_class_Fallopian_tube.log):_ 

WARNING - No valid ID provided for '', label: Fibroblast, user_label: 

![image (1)](https://user-images.githubusercontent.com/2208124/192281106-ee726f21-828d-46a9-b919-0e9c9c3a6fb6.png)

**Comment by emquardokus** [comment]
Given that the fallopian tube, uterus, and ovary tables use a different creation process, "fixing" the final table doesn't fix it forever.  They use the ASCT+B generator Python script and an input table of terms.  For those, if you all the issues, I'll forward them to the authors, who were also the ones who made that script. I'll forward in my comments to this group. Thanks.  Any other issues?

**Comment by anitacaron** [comment]
I'm going to close this issue in favour of #41 which is a complete list.
