### ISSUE TITLE
Use of obsolete Muller cell

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#42]
From the _[2022-09-20 release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-09-20/logs/error_class_Eye.log)_: 

#### WARNING - Different labels found for [CL:0011107](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0011107). Uberongraph: obsolete Muller cell ; ASCT+b table: Muller glia

This CL term was replaced by [CL:0000636](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000636)

**Comment by emquardokus** [comment]
1.	Corrected 1 instance of obsolete CL ID mapping for Muller glia CL_0011107 - Muller glia This one is the obsolete Muller cell
Updated mapping to current CL ID CL:0000636 Mueller cell. This cell had been mapped to an obsolete cell in CL CL:0011107
