### ISSUE TITLE
Relationship in table is reversed: Uberon has thymus subcapsular epithelium subClassOf thymus epithelium

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#44]
From [2022-09-20 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-09-20/logs/class_Thymus_log.tsv): 

row | s | slabel | user_slabel | o | olabel | user_olabel
--| -- | -- | -- | -- | -- | --
61 | UBERON:0003846 | thymus epithelium | thymus epithelium | UBERON:0006936 | thymus subcapsular epithelium | thymus subcapsular epithelium

From [ASCT+B Thymus 1.3](https://docs.google.com/spreadsheets/d/13VmRAofv85ZapJgmtHAVO67ICY4nK1FOugkTKV8_eoM/edit?pli=1#gid=863370556):

row| AS/4 | AS/4/LABEL | AS/4/ID | AS/5 | AS/5/LABEL | AS/5/ID
-- | -- | -- | -- | -- | -- | --
28 | thymus subcapsular epithelium | thymus subcapsular epithelium | UBERON:0006936 | thymus epithelium | thymus epithelium | UBERON:0003846

The order in the ASCT+B table is reversed. The left-side term (AS/4) should always be on the upper level than the right-side term (AS/5).

It should be:

row| AS/4 | AS/4/LABEL | AS/4/ID | AS/5 | AS/5/LABEL | AS/5/ID
-- | -- | -- | -- | -- | -- | --
28 | thymus epithelium | thymus epithelium | UBERON:0003846 | thymus subcapsular epithelium | thymus subcapsular epithelium | UBERON:0006936

**Comment by emquardokus** [comment]
@anitacaron fixed the order for the one instance, but there were several instances of thymus subcapsular epithelium where thymus epithelium needed to come before it, but wasn't there; added AS/7 columns to accommodate fixing all instances the same way.  Rows 28-36 edited to fix issue. done.
