### ISSUE TITLE
[Ovary] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#45]
From the report listing CT terms without IDS: [2022-10-03 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-03/logs/new_cl_terms_Ovary.tsv)

Some of the CL names in the report already exist in Cell Ontology:

| Terminal AS/ID | Terminal AS/label | Terminal AS/user_label | CL Name     | CL term    | OLS link                                                                                              |
|----------------|-------------------|------------------------|-------------|------------|-------------------------------------------------------------------------------------------------------|
| UBERON:0002512 | corpus luteum     | corpus luteum          | luteal cell | CL:0000175 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000175 |
| UBERON:0002512 | corpus luteum     | corpus luteum          | theca cell  | CL:0000503 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000503 |
| UBERON:0000156 | theca externa     | theca externa          | theca cell  | CL:0000503 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000503 |
| UBERON:0000157 | theca interna     | theca interna          | theca cell  | CL:0000503 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000503 |

**Comment by emquardokus** [comment]
These were mapped by me and shared earlier with Ovary team my email on April 15, 2022; they updated their table to match this, but use a Input/Output file with Python script method, which does not immediately put it into the google sheet linked ot the CCF-Tools/google doc draft.  I updated the Ovary_v1.2_DRAFT to reflect the changes on 10-13-2022; this can be closed.

**Comment by anitacaron** [comment]
Thank you, @emquardokus! I confirm that in the [2022-10-10 release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-10/logs/new_cl_terms_Ovary.tsv), the unmapped terms above are not listed.
