### ISSUE TITLE
[Small intestine] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#47]
From the report listing CT terms without IDS: _[2022-10-03 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-03/logs/new_cl_terms_Small_intestine.tsv)_

Some of the CL names in the report already exist in Cell Ontology:

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0008346 | duodenal epithelium     | Epithelium                                           | tuft cell                   | CL:0009080 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0009080 |
| 2 | UBERON:0008346 | duodenal epithelium     | Epithelium                                           | absorptive                  | CL:0000212 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000212 |
| 3 | UBERON:0008346 | duodenal epithelium     | Epithelium                                           | enterocyte                  | CL:0000584 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000584 |
| 4 | UBERON:0008346 | duodenal epithelium     | Epithelium                                           | stem cell                   | CL:0000034 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000034 |
| 5 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | endothelial                 | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |
| 6 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | myofibroblast               | CL:0000186 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000186 |
| 7 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | fibroblast                  | CL:0000057 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000057 |
| 8 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | B cell                      | CL:0000236 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000236 |
| 9 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | plasma                      | CL:0000786 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000786 |
| 10 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | macrophage                  | CL:0000235 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000235 |
| 11 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | eosinophil                  | CL:0000771 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000771 |
| 12 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | mast cell                   | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 13 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | neutrophil                  | CL:0000775 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000775 |
| 14 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | natural killer (NK) cell    | CL:0000623 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000623 |
| 15 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | dendritic cell (DC)         | CL:0000451 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000451 |
| 16 | UBERON:0015834 | duodenum lamina propria | Lamina propria/Gut associated lymphoid tissue (GALT) | innate lyphoid cell (ILC)   | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 17 | UBERON:0003336 | serosa of duodenum      | serosa                                               | mesothelial                 | CL:0000077 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000077 |
| 18 | UBERON:0003336 | serosa of duodenum      | serosa                                               | fibroblasts                 | CL:0000057 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000057 |
| 19 | UBERON:0003336 | serosa of duodenum      | serosa                                               | endothelial cells           | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |
| 20 | UBERON:0000400 | jejunal epithelium      | Epithelium                                           | Paneth                      | CL:0000510 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000510 |
| 21 | UBERON:0000400 | jejunal epithelium      | Epithelium                                           | endocrine                   | CL:0000163 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000163 |
| 22 | UBERON:0000400 | jejunal epithelium      | Epithelium                                           | absorptive                  | CL:0000212 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000212 |
| 23 | UBERON:0000400 | jejunal epithelium      | Epithelium                                           | enterocytes                 | CL:0000584 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000584 |
| 24 | UBERON:0000400 | jejunal epithelium      | Epithelium                                           | Tuft cells                  | CL:0009080 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0009080 |
| 25 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | endothelial                 | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |
| 26 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | myofibroblasts              | CL:0000186 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000186 |
| 27 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | fibroblasts                 | CL:0000057 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000057 |
| 28 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | B cell                      | CL:0000236 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000236 |
| 29 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | macrophages                 | CL:0000235 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000235 |
| 30 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | eosinophils                 | CL:0000771 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000771 |
| 31 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | mast cells                  | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 32 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | neutrophils                 | CL:0000775 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000775 |
| 33 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | NK cells                    | CL:0000623 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000623 |
| 34 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | DCs                         | CL:0000451 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000451 |
| 35 | UBERON:0000399 | jejunal mucosa          | mucosa                                               | ILCs                        | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 36 | UBERON:0003333 | submucosa of jejunum    | submucosa                                            | endoethlial                 | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |
| 37 | UBERON:0012377 | muscle layer of jejunum | muscularis externa                                   | Interstitial cells of Cajal | CL:0002088 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002088 |
| 38 | UBERON:0012377 | muscle layer of jejunum | muscularis externa                                   | fibroblasts                 | CL:0000057 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000057 |
| 39 | UBERON:0012377 | muscle layer of jejunum | muscularis externa                                   | endothelial                 | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |
| 40 | UBERON:0003337 | serosa of jejunum       | serosa                                               | mesothelial                 | CL:0000077 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000077 |
| 41 | UBERON:0003337 | serosa of jejunum       | serosa                                               | fibroblasts                 | CL:0000057 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000057 |
| 42 | UBERON:0003337 | serosa of jejunum       | serosa                                               | endothelial cells           | CL:0000115 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000115 |

**Comment by emquardokus** [comment]
@anitacaron 
All cell types listed above were added to Small_Intestine_v1.1_DRAFT to be published in 4th HRA release
Other cells also mapped by me that were not above are as follows: 

M cell | M cell of gut | CL:0000682
epithelial stem cells | epithelial fate stem cell | CL:0000036

Remaining cells to be mapped for small intestine are as follows: will be working with NEW SMEs for both intestine tables for next release. Cell types too general, need to harmonize with Organ Mapping Antibody Panel cell types.
CD4+ T
regulatory CD4+ T
CD8+ T
nerve
muscle

**Comment by anitacaron** [comment]
Thank you, Ellen!
