### ISSUE TITLE
[Skin] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#51]
From the report listing CT terms without IDS: _[2022-10-10 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-10/logs/new_cl_terms_Skin.tsv)_

Some of the CL names in the report already exist in Cell Ontology:

TABLE UPDATED 2023-11-01

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0008198 | Nail plate        | Nail plate             | Keratinocyte (Onychocyte) | CL:4033056 | https://www.ebi.ac.uk/ols4/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4033056 |
| ~2~ | ~UBERON:0002067~ | ~dermis~            | ~Dermis~                 | ~perineurial cells~         | ~CL:0002576~ | ~https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002576~ |
| ~3~ | ~UBERON:0002072~ | ~hypodermis~        | ~Subcutaneous~           | ~Perineural cell~           | ~CL:0002576~ | ~https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002576~ |

**Comment by anitacaron** [comment]
UPDATE:

Checking the [latest report](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2023-11-01/logs/Skin/new_cl_terms_Skin.tsv), Keratinocyte is still in there. Could you please check if this is a valid mapping for this case, @aleixpuigb?

**Comment by aleixpuigb** [comment]
I added [onychocyte](http://purl.obolibrary.org/obo/CL_4033056) for the last release. Is Ubergraph updated?

UPDATE 
Not in the table yet

**Comment by anitacaron** [comment]
Ah, ok, I updated the table to add your new term instead.

**Comment by anitacaron** [comment]
[Validation report on 2024-04-24](https://hubmapconsortium.github.io/ccf-validation-tools/Skin/graph/): onychocyte was added.

![Screenshot 2024-04-25 at 16 16 38](https://github.com/obophenotype/asct-b_validation/assets/2208124/a0f5d32f-e1a2-4ed7-8479-c5f46d782230)
