### ISSUE TITLE
[Blood] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#52]
From the report listing CT terms without IDS: _[2022-10-10 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-10/logs/new_cl_terms_Blood.tsv)_

Some of the CL names in the report already exist in Cell Ontology:

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0000178 | Blood             | Blood                  | CD4 T cell memory                 | CL:0000897 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000897 |
| 2 | UBERON:0000178 | Blood             | Blood                  | CD4 T cell effector memory CD45RA | CL:0000905 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000905 |
| 3 | UBERON:0000178 | Blood             | Blood                  | CD8 T cell memory                 | CL:0000909 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000909 |
| 4 | UBERON:0000178 | Blood             | Blood                  | mature CD8 T cell                 | CL:0002437 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002437 |

**Comment by emquardokus** [comment]
@anitacaron 
I just looked up CL:0000312 in OLS and it gives a very different identity than you list in this report, how is this possible?  
[keratinocyte](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000312)CL:0000312

![Image](https://user-images.githubusercontent.com/47257000/195902728-0c112a4d-7624-40eb-be66-ba5358c60b2a.png)


When I look for "CD4 T cell memory" in OLS Cell Ontology, there is not exact match, but several possibilities that require immune cell expertise to disambiguate.

==
"CD4 T cell effector memory CD45RA" is in ASCT+B table; the protein biomarker set has CD45RA positive as opposed to negative, this is what you've mapped it to here: effector memory CD4-positive, alpha-beta T cell CL:0000905, which in the definition states "CD4-positive, alpha-beta memory T cell with the phenotype CCR7-negative, CD127-positive, **CD45RA-negative**, CD45RO-positive, and CD25-negative. [ http://purl.obolibrary.org/obo/go/references/0000031 http://www.ncbi.nlm.nih.gov/pubmed/22343568 GOC : add GOC : tfm GOC : pam ] "

What is the evidence used to map this?

===
CD8 T cell memory in ASCT+B table--> CD8-positive, alpha-beta memory T cell CL:0000909

===
mature CD8 T cell in ASCT+B table--> [mature CD8 single-positive thymocyte](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002437)

===

Will double check with authors.

**Comment by emquardokus** [comment]
Blood v1.3 DRAFT 
Added mapping to 2 instances of CD4 T cell memory (note that biomarkers are different; likely subtypes; need to ask author for clarity on this). 

CD4 T cell memory | CD4-positive, alpha-beta memory T cell | CL:0000897
-- | -- | --
CD4 T cell memory | CD4-positive, alpha-beta memory T cell | CL:0000897

**Comment by anitacaron** [comment]
UPDATE:

The last report listing CT terms without IDS: [2023-10-31 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2023-10-25/logs/Blood/new_cl_terms_Blood.tsv) is empty, so all terms were mapped.
