### ISSUE TITLE
[Prostate] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#53]
From the report listing CT terms without IDS: _[2022-10-10 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-10/logs/new_cl_terms_Prostate.tsv)_

Some of the CL names in the report already exist in Cell Ontology as a general type. There's a work in progress to create compound CL types, combining location and cell type, as listed in the table:

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0004184 | prostate gland stroma | prostate stroma        | vascular smooth muscle            | CL:0000359 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000359 |
| 2 | UBERON:0004184 | prostate gland stroma | prostate stroma        | prostate perictye                 | CL:0000669 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000669 |
| 3 | UBERON:0001335 | prostatic urethra     | prostatic urethra      | basal cell of prostatic urethra   | CL:0000646 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000646 |
| 4 | UBERON:0001335 | prostatic urethra     | prostatic urethra      | club cell of prostatic urethra    | CL:4032000 | New term added in 2022-09-15 CL release. CL version in OLS is from the previous release. https://ontobee.org/ontology/CL?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4032000 |
| 5 | UBERON:0001335 | prostatic urethra     | prostatic urethra      | hillock cell of prostatic urethra | CL:0017011 | New term added in 2022-10-28 CL release. https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0017011 |

**Comment by emquardokus** [comment]
@anitacaron 
CL:0000669 is just pericyte, not prostate pericyte, is this the desired to map to generic term?
**There are tickets that were merged a while ago for CL for these: **
club cell of prostatic urethra July 15, 2022 added: https://github.com/obophenotype/cell-ontology/issues/1133
hillock cell of prostatic urethra PR and merge done August 25, 2022 https://github.com/obophenotype/cell-ontology/issues/1134

**Comment by anitacaron** [comment]
**_prostate pericyte_**: we identified many cases where we need to create a cell type related to location (https://github.com/hubmapconsortium/ccf-ontology/issues/16), and we can bulk add them using a ROBOT template. That's why I suggested changing to a generic pericyte.

**_club cell of prostatic urethra_**: Sorry, I didn't find the CL term in OLS because it's not showing the last CL release. I'll update the table here.

**_hillock cell of prostatic urethra_**: The PR linked to the NTR issue for `hillock cell of prostatic urethra` is not creating this term, but another 2, one generic hillock cell and one related to respiratory.

**Comment by anitacaron** [comment]
@emquardokus, _**hillock cell of prostatic urethra**_ was finally added in the last CL release. I've updated the table here with its CURIE.

**Comment by anitacaron** [comment]
UPDATE:

Checking the [latest report](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2023-11-01/logs/Prostate/new_cl_terms_Prostate.tsv), all terms are not there, except _*basal cell of prostatic urethra*_, which was mapped to a general term _*basal cell*_, but it's important to be specific in this case.
