### ISSUE TITLE
[Heart] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#55]
From the report listing CT terms without IDS: _[2022-10-17 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-17/logs/new_cl_terms_Heart.tsv)_

Some of the CL names in the report already exist in Cell Ontology:

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0002078 | right cardiac atrium       | right atrium           | lymphatic endothelial cell                 | CL:0002138 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002138 |
| 2 | UBERON:0002078 | right cardiac atrium       | right atrium           | pericyte                                   | CL:0000669 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000669 |
| 3 | UBERON:0002078 | right cardiac atrium       | right atrium           | telocyte (interstitial like cell of cajal) | CL:0017004 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004 |
| 4 | UBERON:0002079 | left cardiac atrium        | left atrium            | mast cell                                  | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 5 | UBERON:0002079 | left cardiac atrium        | left atrium            | lymphatic endothelial cell                 | CL:0002138 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002138 |
| 6 | UBERON:0002079 | left cardiac atrium        | left atrium            | B lymphocyte                               | CL:0000945 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000945 |
| 7 | UBERON:0002079 | left cardiac atrium        | left atrium            | ILC                                        | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 8 | UBERON:0002079 | left cardiac atrium        | left atrium            | endocardial                                | CL:0002350 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002350 |
| 9 | UBERON:0001982 | capillary                  | vasculature            | pericyte                                   | CL:0000669 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000669 |
| 10 | UBERON:0001979 | venule                     | vasculature            | pericyte                                   | CL:0000669 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000669 |
| 11 | UBERON:0002079 | left cardiac atrium        | left atrium            | telocyte (interstitial like cell of cajal) | CL:0017004 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004 |
| 12 | UBERON:0006566 | left ventricle myocardium  | myocardium             | Purkinje fiber cell                        | CL:0002068 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002068 |
| 13 | UBERON:0006566 | left ventricle myocardium  | myocardium             | telocyte (interstitial like cell of cajal) | CL:0017004 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004 |
| 14 | UBERON:0006566 | left ventricle myocardium  | myocardium             | mast cell                                  | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 15 | UBERON:0006566 | left ventricle myocardium  | myocardium             | lymphatic endothelial cell                 | CL:0002138 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002138 |
| 16 | UBERON:0006566 | left ventricle myocardium  | myocardium             | B lymphocyte                               | CL:0000945 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000945 |
| 17 | UBERON:0006566 | left ventricle myocardium  | myocardium             | ILC                                        | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 18 | UBERON:0006566 | left ventricle myocardium  | myocardium             | endocardial                                | CL:0002350 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002350 |
| 19 | UBERON:0002094 | interventricular septum    | septum                 | Purkinje fiber cell                        | CL:0002068 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002068 |
| 20 | UBERON:0002094 | interventricular septum    | septum                 | telocyte (interstitial like cell of cajal) | CL:0017004 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004 |
| 21 | UBERON:0002094 | interventricular septum    | septum                 | mast cell                                  | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 22 | UBERON:0002094 | interventricular septum    | septum                 | lymphatic endothelial cell                 | CL:0002138 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002138 |
| 23 | UBERON:0002094 | interventricular septum    | septum                 | B lymphocyte                               | CL:0000945 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000945 |
| 24 | UBERON:0002094 | interventricular septum    | septum                 | ILC                                        | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 25 | UBERON:0002094 | interventricular septum    | septum                 | endocardial                                | CL:0002350 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002350 |
| 26 | UBERON:0006567 | right ventricle myocardium | myocardium             | mast cell                                  | CL:0000097 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000097 |
| 27 | UBERON:0006567 | right ventricle myocardium | myocardium             | lymphatic endothelial cell                 | CL:0002138 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002138 |
| 28 | UBERON:0006567 | right ventricle myocardium | myocardium             | B lymphocyte                               | CL:0000945 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000945 |
| 29 | UBERON:0006567 | right ventricle myocardium | myocardium             | ILC                                        | CL:0001065 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001065 |
| 30 | UBERON:0006567 | right ventricle myocardium | myocardium             | endocardial                                | CL:0002350 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002350 |
| 31 | UBERON:0006567 | right ventricle myocardium | myocardium             | Purkinje fiber cell                        | CL:0002068 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002068 |
| 32 | UBERON:0002080 | heart right ventricle      | right ventricle        | telocyte (interstitial like cell of cajal) | CL:0017004 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0017004 |
| 33 | UBERON:0002080 | heart right ventricle      | right ventricle        | Purkinje fiber cell                        | CL:0002068 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002068 |

**Comment by emquardokus** [comment]
Josef Hardi  [5:48 PM] November 8, 2022 Hi all, I'm revisiting my CCF pipeline code and found these invalid IDs:
CL:0002542 - endothelial cell
1. I tracked 20 instances of this to the Heart_v1.2_DRAFT table
I double checked CL and this is an "has alternative id" for CL:1000413, replaced all 20 instances with CL:1000413.

**Comment by emquardokus** [comment]
@anitacaron 11-17-2011 updated Heart_v1.2_DRAFT
4 instances capillary endothelial cell FMA:67756 replaced with CL:0002144
4 instances of myocardium of right atrium FMA:83531 with cardiac muscle of right atriumUBERON:0003379
6 instances of Myocardium of interventricular septum FMA:83539 with cardiac muscle tissue of interventricular septum UBERON:0003383
5 instances unmapped mast cell, add mast cell CL:0000097
9 instances unmapped pericyte, add pericyte 	CL:0000669
Row 193 moderator band AS has telocyte: Replaced 1 instance of telocyte (interstitial like cell of cajal) heart valve cell	CL:1000147 with telocyte 
5 instances of lymphatic endothelial cell unmapped; add lymphatic endothelial cell CL:0002138
5 instances unmapped NK/T lymphocyte Add: immature NK T cell CL:0000914
5 instances unmapped B lymphocyte mapped to B cell CL:0000236
4 instances unmapped ILC mapped to innate lymphoid cell	CL:0001065
4 instance unmapped to endocardial mapped to endocardial	CL:0002350
4 instance unmapped Purkinje fiber cell mapped to Purkinje myocyte CL:0002068

**Comment by anitacaron** [comment]
Hi Ellen, thank you for all the edits! I updated the table above to track all your changes.
Did you also update the 5 instances for the unmapped telocyte?

You comment on one instance that is not listed here.
> Row 193 moderator band AS has telocyte: Replaced 1 instance of telocyte (interstitial like cell of cajal) heart valve cell CL:1000147 with telocyte

**Comment by emquardokus** [comment]
@anitacaron 
All instances of telocytes were mapped;however, the instance I refer to here was a situation where telocyte was in the wrong anatomical structure, so I replaced it with the correct  heart valve cell CL:1000147.

**Comment by anitacaron** [comment]
Thank you, Ellen. I've updated the table above. I'll double-check in the following validation release.
