### ISSUE TITLE
[Knee] Unmapped CL terms

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#56]
From the report listing CT terms without IDS: _[2022-10-17 Release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-10-17/logs/new_cl_terms_Knee.tsv)_

Some of the CL names in the report already exist in Cell Ontology:

| N | Terminal AS/ID | Terminal AS/label          | Terminal AS/user_label | CL Name                                    | CL term    | OLS link                                                                                              |
|----|----------------|----------------------------|------------------------|--------------------------------------------|------------|-------------------------------------------------------------------------------------------------------|
| 1 | UBERON:0007195 | stroma of bone marrow | Bone Marrow Stroma | vascular endothelial cells | CL:0002139 | https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002139 |

**Comment by emquardokus** [comment]
@anitacaron this whole knee table is in the process of a major rework by author; will revisit for April 2023 CCF release

**Comment by anitacaron** [comment]
UPDATE:

Checking the [latest report](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2023-11-01/logs/Knee/new_cl_terms_Knee.tsv), this term is not listed anymore, and it seems all the terms are truly new.
