### ISSUE TITLE
[Replace FMA with CL] FMA:62362 Glycinergic amacrine cell of retina -> CL:4030028 'glycinergic amacrine cell'

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#61]
In the [2022-10-24 report](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/error_class_Eye.log), there's a warning message:

**WARNING - No valid ID provided for 'FMA:62362', label: Glycinergic amacrine cell of retina, user_label: Glycinergic Amacrine Cell**

Recently, the term CL:4030028 [was added](https://github.com/obophenotype/cell-ontology/issues/1714), but still not available in the last CL release.

**Comment by emquardokus** [comment]
any idea when the next CL release might be where it would become available?

**Comment by emquardokus** [comment]
Related issues: 
[NTR]retinal ganglion specific cell type: midget ganglion cell of retina #1728 https://github.com/obophenotype/cell-ontology/issues/1728
[NTR] retinal ganglion specific cell type parasol ganglion cell of retina #1729  https://github.com/obophenotype/cell-ontology/issues/1729

**Comment by anitacaron** [comment]
> @anitacaron any idea when the next CL release might be where it would become available?

The two terms are already available in the CL 

https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_4030028
https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_4030027

**Comment by emquardokus** [comment]
Great, the new cell types requested are specific types to superclass.

**Comment by anitacaron** [comment]
The cell is available in the v1.3 DRAFT.

<img width="1192" alt="Screenshot 2023-03-29 at 15 20 35" src="https://user-images.githubusercontent.com/2208124/228568903-11bf1c0a-aba0-49f1-a848-467c653eae53.png">
