### ISSUE TITLE
Remove CL:0008364

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/asct-b_validation#64]
Following the report in the [2022-10-07 release](https://github.com/hubmapconsortium/ccf-validation-tools/blob/v2022-11-07/logs/error_class_Large_intestine.log):

__WARNING - Unrecognised UBERON/CL/PCL entity 'CL:0008364'__

Please, remove this term because it doesn't exist in Cell Ontology.

**Comment by emquardokus** [comment]
See recent comments on large intestine https://github.com/obophenotype/asct-b_validation/issues/11
I resolved this issue before you made this issue.

**Comment by anitacaron** [comment]
Great! I noticed it some time ago but didn't realise I didn't create an issue to track.
